### ISSUE TITLE
 Invalid magic number; corrupt file?

### ISSUE THREAD

**Issue by wanghangege** [Loahit5101/PointPillars-Camera-LiDAR-Fusion#3]
thanks for your good job, I have some doubts about some samll code problems. firstly, in the code (line **180** in </CLOC_fusion/tool/dataset.py>):
"
            return fusion_input,tensor_index,(self._3d_path+"/"+idx+".pt")

"
 is the ".pt" should be ".pkl" ? so we can get 3d results; when I change to ".pkl", the next problem happened:
"
`Traceback (most recent call last):
  File "/cloc_fusion/CLOC_fusion/train.py", line 200, in <module>
    eval(fusion_layer, val_data, logf, log_path, epoch, cfg, eval_set, logger)
  File "/cloc_fusion/CLOC_fusion/train.py", line 110, in eval
    _3d_result = torch.load(path[0])[0]
  File "~/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "~/ib/python3.7/site-packages/torch/serialization.py", line 779, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?`
" 
could you help me to solve it ? thank you !

**Comment by Loahit5101** [comment]
Hi, thank you for your interest. PointPillars generates 3D candidates in .pkl files. CLOCs generates dataset using the .pkl files in the form of .pt files, so no need to change that line.

**Comment by Muhammadadeelaltaf** [comment]
Hello, I am trying to generate the data by sudo python generate_data.py
 for CLOC_fusion but facing the error:  /home/adeel/.local/lib/python3.6/site-packages/numba/errors.py:137: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)  Traceback (most recent call last):
  File "generate_data.py", line 3, in <module>
    from tool.dataset import clocs_data
  File "/home/adeel/PointPillars-Camera-LiDAR-Fusion/CLOC_fusion/tool/dataset.py", line 7, in <module>
    from pcdet.datasets.kitti.kitti_object_eval_python.eval import d3_box_overlap
  File "/home/adeel/PointPillars-Camera-LiDAR-Fusion/CLOC_fusion/pcdet/datasets/__init__.py", line 8, in <module>
    from .kitti.kitti_dataset import KittiDataset
  File "/home/adeel/PointPillars-Camera-LiDAR-Fusion/CLOC_fusion/pcdet/datasets/kitti/kitti_dataset.py", line 5, in <module>
    from skimage import io
ModuleNotFoundError: No module named 'skimage'
 Infact, i have installed this skimage module and verified it, it shows me the version 0.20.0 as well. Please guide me in this regard. Thank you.
